### ISSUE TITLE
columns are rendered as rows in bootstrap 4.4.1 + tinymce5

### ISSUE THREAD

**Issue by kenvanhuffel** [jeffhehe/tiny-bs-grid#1]
First of all, thank u for your effort! I have a problem with the plugin. Im using tinymce 5 and bootstrap 4.4.1.
The plugin is visible in my tinymce, and I can insert, update, and remove grids.
BUT... the grids are not showing columns near eachother. If I choose 2 columns, it renders 2 rows.
any idea why this is, or how to fix this?

function init_tinymce_body()
{
    var tinymce_html = '';
	tinymce_html += '<textarea id="tinymce_body" name="tinymce_body" class="tox-target">';
	tinymce_html += '</textarea>';
    $("#tinymce_body_container").empty();
    $("#tinymce_body_container").append(tinymce_html);
	
    $('textarea#tinymce_body').tinymce({
		selector: '#tinymce_body',
		toolbar: 'advlist | autolink | link image media | lists charmap | print preview | bootstrap4grid addImage addLink',
		plugins: 'advlist autolink link image media lists charmap print preview bootstrap4grid',
		height: 500,
		external_plugins: {
			'bootstrap4grid': '../../../../assets/plugins/custom/tinymce/plugins/bootstrap4grid/plugin.js' //local path to plugin.min.js file
		},
		content_css: [
			'https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' 
		],
		//grid_preset: 'Bootstrap3', //toolbar:grid_insert //plugins:grid
		setup: function (editor) { // on the setup of the TinyMCE plugin, add a button with the alias 'addImage'
			editor.ui.registry.addButton('addImage', {
				text: 'Add Image', // the text to display alongside the button
				icon: 'image', // the icon to display alongside the button
				onAction: function () {
					activeTextArea = editor; // onclick of this button, set the active textarea to that of which the button was pressed
					$('#modal_image_picker').modal('show'); // show the file picker modal
				}
			});
			
			editor.ui.registry.addButton('addLink', {
				text: 'Add Link', // the text to display alongside the button
				icon: 'link', // the icon to display alongside the button
				onAction: function () {
					activeTextArea = editor; // onclick of this button, set the active textarea to that of which the button was pressed
					$('#modal_doc_picker').modal('show'); // show the file picker modal
				}
			});
		}
    });
}

![Knipsel](https://user-images.githubusercontent.com/61052172/190326619-2221cf9f-6167-4658-871b-a738759a8c72.JPG)

**Comment by jeffhehe** [comment]
The columns are stacking as rows when the viewport is less than the breakpoints for the grids. This is the responsive grid layout feature from Bootstrap. In this case your viewport is the width of the editor, the view breakpoint is your selection of the "target screen" in the plugin, for example >=992px for large screen. You can expand your editor width by drag the right bottom corner of the editor or use Fullscreen view of the editor from View -> Fullscreen.

**Comment by kenvanhuffel** [comment]
> The columns are stacking as rows when the viewport is less than the breakpoints for the grids. This is the responsive grid layout feature from Bootstrap. In this case your viewport is the width of the editor, the view breakpoint is your selection of the "target screen" in the plugin, for example >=992px for large screen. You can expand your editor width by drag the right bottom corner of the editor or use Fullscreen view of the editor from View -> Fullscreen.

Thanks for the clarification! stupid of me ;) its bootstrap: so its obvious the columns trap and grind based on view port.
Thanks again, i gonna try it again and make the tinymce bigger as content.

**Comment by jeffhehe** [comment]
Not a problem at all. I didn’t actively monitor my github account, sorry about replying late. You are welcome to report any issue you find. Thank you for reaching out.
